### PR TITLE
Updating styling. Used pureCSS classes, moved CSS out of HTML file

### PR DESCRIPTION
**Pull request by MattMaginniss**
Hey Jack. Loved the page. I saw you post on r/chess and thought it could be just a little cleaner. I hope you don't mind any of the changes.

- Added a gutter on the left and right on the desktop because it kind of looked hilarious on my 4k monitor and all the stuff was squished to one side.
- Added pureCSS classes since they were already imported but didn't seem to be used
- Changed the text area from disabled to readonly, which is basically the same but doesn't have a weird icon as a cursor
- Moved CSS to an independent file as it is is kind of just cleaner

As I said, I hope you don't mind the changes. Thanks for the cool site!

### CODE REVIEW

**Comment by jkingsman** [comment]
Thanks so much; that's wonderful! I'm on my mobile and will check+merge in a little bit but looks like the diff is large -- maybe a line ending or indent change? If it's converting to unix line endings it's fine to leave as it is. Thanks again!!!!

**Comment by MattMaginniss** [comment]
No worries! Of course check it out and decide your thoughts on the changes.

I have no idea why it looks like I changed every single line. If you look at commit #5c03acb the only things that should have changed was the textarea. (I added  &#013;&#010; to generate the line break rather than just hitting enter in the HTML as its a bit cleaner) I wasn't changing the files line endings. Maybe it was a line ending difference because I use VSCode on Windows and you use something else but I didn't purposefully change everything.

**Comment by jkingsman** [comment]
Ah no worries! Looks like I was the one with Windows line endings; your line endings are correct and mine were wrong.

This is a gorgeous change -- thank you for the work!

**Comment by MattMaginniss** [comment]
You're welcome! I'm happy you like it! Have a good night!

**Pull request merged**
